### ISSUE TITLE
Why the color changes?

### ISSUE THREAD

**Issue by LangInteger** [jasonlong/isometric-contributions#185]
![image](https://user-images.githubusercontent.com/17768055/139541652-fbdc2994-73c3-4043-975d-9c5f5b1f747d.png)

I remember the picture once was mainly with green color. Why does it change to yellow?

**Comment by shuuji3** [comment]
Hi, this color change is GitHub's Halloween easter egg feature since today is Halloween day. 🎃🙂

You can see their "Happy Halloween" message when you changing to 2D mode:

<img width="721" alt="Screen Shot 2021-10-31 at 3 39 18" src="https://user-images.githubusercontent.com/1425259/139554888-1eeea146-fdc1-4076-ac1a-b95c90969339.png">

**Comment by LangInteger** [comment]
Haha``thx @shuuji3

**Comment by shuuji3** [comment]
Welcome! 😄
