### ISSUE TITLE
Sometimes it gets stuck

### ISSUE THREAD

**Issue by David-xian66** [jasonlong/isometric-contributions#239]
Can you optimize the icon generation, sometimes into the home page will be stuck
🤔

**Comment by jasonlong** [comment]
@David-xian66 Can you give any additional information about what you're seeing and when it happens?

**Comment by David-xian66** [comment]
> @David-xian66 Can you give any additional information about what you're seeing and when it happens?


 When I load a user's home page, the page loads and the browser freezes for a second or two

**Comment by jasonlong** [comment]
I haven't been able to identify any freezes on my end. There is a noticeable delay when rendering the 3d graph because the extension has to wait for the normal page to load before looping over the 2d graph and injecting the 3d version. If this is what you're seeing, I don't think there's much I can do about that.

**Comment by David-xian66** [comment]
It doesn't seem to be a question of "isometric-contributions“, but thank you all the same
