### ISSUE TITLE
Should the average count consider the whole current year?

### ISSUE THREAD

**Issue by FdelMazo** [jasonlong/isometric-contributions#316]
This are my 2024 contributions so far

![image](https://github.com/jasonlong/isometric-contributions/assets/25667102/b36dfeee-0502-4157-8a48-3c140fe9e8bf)

The graph shows that I have 1.24 commits per day on average, which comes from the `453/365` division. Considering the year isn't over, maybe it's more relevant to show the average commits per day so far? (as in, `453/178=2.5`, on June 26th).

Let me know what you think @jasonlong and I'll draft a PR!

**Comment by jasonlong** [comment]
Hey @FdelMazo, sorry for the delay responding. I hadn't noticed this before since it only happens when you click on the current year. But you're right, it would be nice to have the current year only take into account days that have passed so far.

Feel free to open a PR. Otherwise, I'll put this on my list to fix soon.
