### ISSUE TITLE
Longest Streak days and count is broken.

### ISSUE THREAD

**Issue by EricFreeman** [jasonlong/isometric-contributions#51]
I suspect this might be when the user has a streak longer than one year, but haven't confirmed this yet.  Personally, my streak is around 800 days now, but it shows as "null - null".

![rip streaks](https://cloud.githubusercontent.com/assets/4977850/15526242/a1c4d36a-21ed-11e6-96f1-924e47c5f5f9.PNG)

**Comment by jasonlong** [comment]
I think this should be fixed with the latest version I posted yesterday (1.0.10). This is what I see on your profile:

![screen shot 2016-05-25 at 8 38 23 am](https://cloud.githubusercontent.com/assets/6104/15540212/2e3821d8-2254-11e6-835d-ba4e0c57d9a1.png)

I'm going to close this for now, but feel free to reopen if you're still seeing the problem.

**Comment by EricFreeman** [comment]
It doesn't go back further than a year like the old GitHub streaks would, but I guess this will scratch the itch for now.  ;)

**Comment by jasonlong** [comment]
Yeah, unfortunately the extension only has access to the data in the chart going back a year.

**Comment by dgw** [comment]
I just installed the extension today, and I am seeing "0 days", "null – null" for my longest streak as well. Is this the same or a new issue?

Chrome 52 (currently bothering me to auto-update to 53), OS X 10.10.5

**Comment by dgw** [comment]
Update: Worked after midnight until I added a contribution for the new day, then went back to displaying "null"s.

**Comment by jasonlong** [comment]
There is some work going on with the contribution chart at GitHub, so I'm going to wait until things settle down before debugging much here.
