### ISSUE TITLE
It seems not work on Safari

### ISSUE THREAD

**Issue by TennyZhuang** [jasonlong/isometric-contributions#64]
![638a600a-640b-4b48-9492-2a1a9b2b47b9](https://cloud.githubusercontent.com/assets/9161438/19837917/ebfa67cc-9efe-11e6-870e-384dbb0332f6.png)

I install the safarixtz file and trust it, but it seems not work?

![0bb1c0f7-e31c-4aa9-b1ec-9caa10eb8f53](https://cloud.githubusercontent.com/assets/9161438/19837930/21d055b4-9eff-11e6-99c3-855378362f27.png)

**Comment by jasonlong** [comment]
Apologies for this confusion. The current Safari version of the extension is very much out-of-date because you now need a paid Apple Developer account to build extensions. Since this is the only thing I'd use it for, I've decided not to spend the $99. I'll update the README with an explanation about this.

**Comment by TennyZhuang** [comment]
Can I build it for myself using the source code ?

**Comment by jasonlong** [comment]
You can install the extension with Extension Builder (Safari > Develop > Extension Builder), but I think it'll only stay loaded for that Safari session. AFAIK, you still need the paid Apple Developer account to build the package so if you have one, you certainly can do so.
