### ISSUE TITLE
Don't load the extension on every pages

### ISSUE THREAD

**Issue by math2001** [jasonlong/isometric-contributions#67]
Hello!

First, thanks for you extension, it's much better like this!

But, when I looked at the code, I've seen that you load it on **every page**, and because you use jquery, it's a pretty useless and heavy load. So I was wondering if you could remove it. 😃 

Thanks again,
Matt

**Comment by jasonlong** [comment]
To allow GitHub Enterprise users to use this plugin, I'm not able to restrict the domains that the plugin runs on (since it can be installed on any domain).

I would, however, like to remove the jquery dependency. That's on my list, so I'm going to close this for now. Feel free to reopen if you like.
